import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { documentUrl, documentName, documentType } = await request.json();

    if (!documentUrl) {
      return NextResponse.json(
        { error: "Document URL is required" },
        { status: 400 }
      );
    }

    // Dynamically import pdf-lib to avoid build-time issues
    const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");

    // Create PDF document
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 800]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    // Add header
    page.drawText("ZenithBooks Document Vault", {
      x: 40,
      y: height - 40,
      size: 20,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    // Add document info
    page.drawText(`Document: ${documentName || "Document"}`, {
      x: 40,
      y: height - 80,
      size: 14,
      font,
    });

    page.drawText(`Type: ${documentType || "File"}`, {
      x: 40,
      y: height - 100,
      size: 12,
      font,
    });

    page.drawText(`Downloaded: ${new Date().toLocaleString()}`, {
      x: 40,
      y: height - 120,
      size: 12,
      font,
    });

    // Add footer
    page.drawText("Generated by ZenithBooks - Secure Document Management", {
      x: 40,
      y: 40,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    // Generate PDF bytes
    const pdfBytes = await pdfDoc.save();

    // Return PDF as response
    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${documentName || "document"}.pdf"`,
      },
    });

  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    );
  }
}

// For backward compatibility, support GET requests
export async function GET() {
  try {
    // Dynamically import pdf-lib to avoid build-time issues
    const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 800]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();

    // Add header
    page.drawText("ZenithBooks Document Vault", {
      x: 40,
      y: height - 40,
      size: 20,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    page.drawText("Sample Document", {
      x: 40,
      y: height - 80,
      size: 14,
      font,
    });

    page.drawText(`Generated: ${new Date().toLocaleString()}`, {
      x: 40,
      y: height - 100,
      size: 12,
      font,
    });

    // Add footer
    page.drawText("Generated by ZenithBooks - Secure Document Management", {
      x: 40,
      y: 40,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="sample-document.pdf"',
      },
    });

  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    );
  }
}
