
"use client";

import Link from "next/link";
import { ArrowLeft, FileText, Shield } from "lucide-react";
import Image from "next/image";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function LegalDocumentsGuidePage() {
  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <Link href="/resources/knowledge-base" className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground">
        <ArrowLeft className="size-4" />
        Back to Knowledge Base
      </Link>
      <div className="text-center">
        <div className="flex items-center justify-center size-16 rounded-full bg-primary/10 mb-4 mx-auto">
            <Shield className="h-8 w-8 text-primary" />
        </div>
        <h1 className="text-3xl font-bold">Legal Documents Guide</h1>
        <p className="text-muted-foreground">How to use the document generation wizards.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Shield /> Document Generators</CardTitle>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <p>The "Legal Documents" section provides a library of wizards designed to help you create common legal and business documents quickly and easily. These tools are perfect for startups, small businesses, and professionals who need to generate standard legal paperwork without starting from scratch.</p>
          <Image src="https://placehold.co/800x400/e2e8f0/64748b?text=Legal+Documents+Library+Screenshot" alt="Document selection screen" width={800} height={400} className="rounded-lg border" data-ai-hint="legal documents library" />
          
          <h4>How It Works:</h4>
          <ol>
            <li><strong>Select a Document:</strong> Choose the type of document you need to create from the library (e.g., Partnership Deed, Offer Letter, NDA).</li>
            <li><strong>Follow the Wizard:</strong> Each document has a step-by-step wizard that will prompt you to enter the necessary information. This typically includes names, addresses, dates, financial figures, and specific clauses.</li>
            <li><strong>AI-Powered Suggestions (where applicable):</strong> For complex documents like Partnership Deeds, you can use the "Suggest Clauses with AI" feature. Based on your described business activity, the AI will recommend relevant legal clauses to include in your agreement.</li>
            <li><strong>Preview & Download:</strong> Once you've filled in all the details, the system generates a live preview of the final document. You can review it, go back and make changes, or print/save it as a PDF.</li>
            <li><strong>Share:</strong> Use the integrated sharing buttons to quickly send the generated document via WhatsApp or other platforms.</li>
          </ol>
           <h4>Disclaimer</h4>
            <p>The documents generated by these tools are based on standard templates. While they are a great starting point, they are not a substitute for professional legal advice. It is always recommended to have a qualified legal professional review any critical agreements before signing.</p>
        </CardContent>
         <CardFooter>
            <Link href="/legal-documents" passHref>
                <Button>Go to Legal Documents</Button>
            </Link>
        </CardFooter>
      </Card>
    </div>
  );
}
