/**
 * Monthly Compliance Services - Plan Definitions
 * ICAI-Compliant: Platform-managed professional resources
 */

import type { CompliancePlan, ComplianceTask } from './types';

// Task definitions for all plans
const coreComplianceTasks: ComplianceTask[] = [
  {
    id: 'monthly_bookkeeping',
    name: 'Monthly Bookkeeping & Journal Entries',
    category: 'Accounting',
    frequency: 'monthly',
    description: 'Complete monthly bookkeeping and journal entries managed by ZenithBooks internal professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'bank_reconciliation',
    name: 'Bank Reconciliation',
    category: 'Accounting',
    frequency: 'monthly',
    description: 'Monthly bank reconciliation managed by platform-managed professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'trial_balance',
    name: 'Trial Balance',
    category: 'Accounting',
    frequency: 'monthly',
    description: 'Monthly trial balance generation',
    priority: 'high',
    autoGenerated: true,
    dependencies: ['monthly_bookkeeping', 'bank_reconciliation'],
  },
  {
    id: 'monthly_pl_bs',
    name: 'Monthly P&L & Balance Sheet',
    category: 'Accounting',
    frequency: 'monthly',
    description: 'Monthly Profit & Loss and Balance Sheet for management use',
    priority: 'high',
    autoGenerated: true,
    dependencies: ['trial_balance'],
  },
  {
    id: 'gstr1_filing',
    name: 'GSTR-1 Filing',
    category: 'GST',
    frequency: 'monthly',
    description: 'Monthly GSTR-1 filing managed by ZenithBooks internal professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'gstr3b_filing',
    name: 'GSTR-3B Filing',
    category: 'GST',
    frequency: 'monthly',
    description: 'Monthly GSTR-3B filing managed by platform-managed professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'gst_reconciliation',
    name: 'GST Liability & ITC Reconciliation',
    category: 'GST',
    frequency: 'monthly',
    description: 'Monthly GST liability and ITC reconciliation',
    priority: 'medium',
    autoGenerated: true,
    dependencies: ['gstr1_filing', 'gstr3b_filing'],
  },
  {
    id: 'compliance_calendar',
    name: 'Compliance Calendar & Reminders',
    category: 'Compliance',
    frequency: 'monthly',
    description: 'Monthly compliance calendar updates and reminders',
    priority: 'medium',
    autoGenerated: true,
  },
];

const statutoryComplianceTasks: ComplianceTask[] = [
  ...coreComplianceTasks,
  {
    id: 'tds_computation',
    name: 'TDS Computation & Challans',
    category: 'Tax',
    frequency: 'monthly',
    description: 'Monthly TDS computation and challan generation managed by ZenithBooks internal professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'tds_quarterly_return',
    name: 'Quarterly TDS Returns',
    category: 'Tax',
    frequency: 'quarterly',
    description: 'Quarterly TDS return filing managed by platform-managed professional team',
    priority: 'high',
    autoGenerated: true,
    dependencies: ['tds_computation'],
  },
  {
    id: 'form16_generation',
    name: 'Form 16 / 16A Generation',
    category: 'Tax',
    frequency: 'annual',
    description: 'Annual Form 16 and 16A generation',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'payroll_processing',
    name: 'Payroll Processing',
    category: 'Payroll',
    frequency: 'monthly',
    description: 'Monthly payroll processing managed by ZenithBooks internal professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'pf_esi_computation',
    name: 'PF, ESI, PT Computation & Challans',
    category: 'Payroll',
    frequency: 'monthly',
    description: 'Monthly PF, ESI, and PT computation and challans',
    priority: 'high',
    autoGenerated: true,
    dependencies: ['payroll_processing'],
  },
  {
    id: 'payroll_reports',
    name: 'Payroll Reports & Payslips',
    category: 'Payroll',
    frequency: 'monthly',
    description: 'Monthly payroll reports and payslip generation',
    priority: 'medium',
    autoGenerated: true,
    dependencies: ['payroll_processing'],
  },
  {
    id: 'compliance_dashboard',
    name: 'Compliance Tracking Dashboard',
    category: 'Compliance',
    frequency: 'monthly',
    description: 'Monthly compliance tracking and status dashboard',
    priority: 'medium',
    autoGenerated: true,
  },
];

const completeComplianceTasks: ComplianceTask[] = [
  ...statutoryComplianceTasks,
  {
    id: 'mca_compliance_tracking',
    name: 'MCA Compliance Tracking',
    category: 'MCA',
    frequency: 'monthly',
    description: 'Monthly MCA compliance tracking managed by ZenithBooks internal professional team',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'annual_roc_filings',
    name: 'Annual ROC Filings',
    category: 'MCA',
    frequency: 'annual',
    description: 'Annual ROC filing management',
    priority: 'high',
    autoGenerated: true,
    dependencies: ['mca_compliance_tracking'],
  },
  {
    id: 'event_based_mca',
    name: 'Event-based MCA Filings',
    category: 'MCA',
    frequency: 'event-based',
    description: 'Event-based MCA filings tracking and preparation',
    priority: 'medium',
    autoGenerated: false, // Manual trigger for events
  },
  {
    id: 'director_kyc',
    name: 'Director KYC Reminders',
    category: 'MCA',
    frequency: 'annual',
    description: 'Annual Director KYC reminders and compliance',
    priority: 'medium',
    autoGenerated: true,
  },
  {
    id: 'compliance_health_score',
    name: 'Compliance Health Score',
    category: 'Compliance',
    frequency: 'monthly',
    description: 'Monthly compliance health score calculation',
    priority: 'low',
    autoGenerated: true,
  },
  {
    id: 'priority_sla',
    name: 'Priority SLA Handling',
    category: 'Service',
    frequency: 'monthly',
    description: 'Priority SLA handling for compliance tasks',
    priority: 'high',
    autoGenerated: true,
  },
  {
    id: 'dedicated_queue',
    name: 'Dedicated Account Queue',
    category: 'Service',
    frequency: 'monthly',
    description: 'Dedicated account queue for compliance tasks (platform-managed team)',
    priority: 'high',
    autoGenerated: true,
  },
];

export const COMPLIANCE_PLANS: Record<CompliancePlanTier, CompliancePlan> = {
  core: {
    id: 'core',
    name: 'Starter Plan',
    description: 'GST Returns + Basic Accounting + Monthly Reports - Perfect for small MSMEs and early startups',
    monthlyPrice: 2999,
    annualPrice: 29990, // ~16% discount
    targetAudience: 'Small MSMEs, early startups',
    includes: [
      'Monthly bookkeeping & journal entries',
      'Bank reconciliation',
      'Trial Balance',
      'Monthly P&L & Balance Sheet (management use)',
      'GSTR-1 filing',
      'GSTR-3B filing',
      'GST liability & ITC reconciliation',
      'GST return documents stored in vault',
      'Compliance calendar & reminders',
      'Monthly compliance reports',
    ],
    excludes: ['TDS', 'Payroll', 'MCA', 'Advanced notices', 'CA review'],
    tasks: coreComplianceTasks,
    features: [
      'Platform-managed delivery by ZenithBooks Compliance Team',
      'All filings logged with audit trails',
      'Documents stored in secure vault',
      'Compliance calendar with reminders',
      'Handled by ZenithBooks Compliance Team',
    ],
  },
  statutory: {
    id: 'statutory',
    name: 'Growth Plan',
    description: 'GST + Accounting + TDS/TCS + Payroll (PF/ESI) + Compliance Calendar - Complete compliance for growing businesses',
    monthlyPrice: 5999,
    annualPrice: 59990, // ~16% discount
    targetAudience: 'Growing businesses',
    includes: [
      'Everything in Starter Plan',
      'TDS computation & challans',
      'Quarterly TDS returns',
      'Form 16 / 16A generation',
      'Payroll processing',
      'PF, ESI, PT computation & challans',
      'Payroll reports & payslips',
      'Compliance tracking dashboard',
      'Compliance calendar & due date reminders',
    ],
    tasks: statutoryComplianceTasks,
    features: [
      'Everything in Starter Plan, PLUS',
      'Full tax compliance management',
      'Complete payroll processing',
      'Advanced compliance dashboard',
      'Platform-managed delivery by ZenithBooks Compliance Team',
      'Handled by ZenithBooks Compliance Team',
    ],
  },
  complete: {
    id: 'complete',
    name: 'Enterprise Plan',
    description: 'Everything in Growth + MCA Compliances + CA Review + Dedicated Account Manager - Full service for funded startups, LLPs, Pvt Ltd companies',
    monthlyPrice: 9999,
    annualPrice: 99990, // ~16% discount
    targetAudience: 'Funded startups, LLPs, Pvt Ltd',
    includes: [
      'Everything in Growth Plan',
      'MCA compliance tracking',
      'Annual ROC filings',
      'Event-based MCA filings (tracking + preparation)',
      'Director KYC reminders',
      'CA review & verification',
      'Compliance health score',
      'Priority SLA handling',
      'Dedicated Account Manager',
      'Dedicated account queue (platform-managed team)',
    ],
    tasks: completeComplianceTasks,
    features: [
      'Everything in Growth Plan, PLUS',
      'Complete MCA compliance',
      'CA review & verification',
      'Event-based filing support',
      'Priority SLA handling',
      'Dedicated Account Manager',
      'Compliance health monitoring',
      'Platform-managed delivery by ZenithBooks Compliance Team',
      'Handled by ZenithBooks Compliance Team',
    ],
  },
};

export const COMPLIANCE_PLAN_IDS = Object.keys(COMPLIANCE_PLANS) as CompliancePlanTier[];

/** MSME Enablement task types (non-filing, can be CM-L1/L2). Use for manual creation or MSME plan. */
export const MSME_ENABLEMENT_TASKS: ComplianceTask[] = [
  { id: 'MSME_REGISTRATION', name: 'MSME Registration', category: 'MSME', frequency: 'event-based', description: 'MSME registration support (Udyam)', priority: 'high', autoGenerated: false },
  { id: 'MSME_STATUS_CHECK', name: 'MSME Status Check', category: 'MSME', frequency: 'event-based', description: 'MSME registration status and verification', priority: 'medium', autoGenerated: false },
  { id: 'TReDS_ONBOARDING_PREP', name: 'TReDS Onboarding Prep', category: 'MSME', frequency: 'event-based', description: 'TReDS platform onboarding preparation', priority: 'high', autoGenerated: false },
  { id: 'LOAN_READINESS_REPORT', name: 'Loan Readiness Report', category: 'MSME', frequency: 'event-based', description: 'Basic loan readiness / bankability report', priority: 'high', autoGenerated: false },
  { id: 'GOVT_SCHEME_ELIGIBILITY', name: 'Govt Scheme Eligibility', category: 'MSME', frequency: 'event-based', description: 'Government scheme eligibility check', priority: 'medium', autoGenerated: false },
  { id: 'BASIC_MIS_REPORT', name: 'Basic MIS Report', category: 'MSME', frequency: 'monthly', description: 'Basic management information report', priority: 'medium', autoGenerated: false },
];

export function getCompliancePlan(tier: CompliancePlanTier): CompliancePlan {
  return COMPLIANCE_PLANS[tier];
}

export function getAllCompliancePlans(): CompliancePlan[] {
  return Object.values(COMPLIANCE_PLANS);
}

/**
 * Get compliance plan with pricing from pricing service
 * Falls back to default pricing if not found in pricing service
 */
export async function getCompliancePlanWithPricing(tier: CompliancePlanTier, pricingService?: any): Promise<CompliancePlan> {
  const plan = COMPLIANCE_PLANS[tier];
  
  if (pricingService?.compliance_plans) {
    const pricingMap: Record<string, number> = {};
    pricingService.compliance_plans.forEach((p: { id: string; price: number }) => {
      pricingMap[p.id] = p.price;
    });
    
    const monthlyKey = `${tier}_monthly`;
    const annualKey = `${tier}_annual`;
    
    return {
      ...plan,
      monthlyPrice: pricingMap[monthlyKey] ?? plan.monthlyPrice,
      annualPrice: pricingMap[annualKey] ?? plan.annualPrice,
    };
  }
  
  return plan;
}

/**
 * Get all compliance plans with pricing from pricing service
 */
export async function getAllCompliancePlansWithPricing(pricingService?: any): Promise<CompliancePlan[]> {
  const plans = getAllCompliancePlans();
  
  if (pricingService?.compliance_plans) {
    const pricingMap: Record<string, number> = {};
    pricingService.compliance_plans.forEach((p: { id: string; price: number }) => {
      pricingMap[p.id] = p.price;
    });
    
    return plans.map(plan => {
      const monthlyKey = `${plan.id}_monthly`;
      const annualKey = `${plan.id}_annual`;
      
      return {
        ...plan,
        monthlyPrice: pricingMap[monthlyKey] ?? plan.monthlyPrice,
        annualPrice: pricingMap[annualKey] ?? plan.annualPrice,
      };
    });
  }
  
  return plans;
}

