/**
 * Monthly Compliance Services - Types
 * ICAI-Compliant: ZenithBooks as principal service provider
 */

import { Timestamp } from 'firebase/firestore';

export type CompliancePlanTier = 'core' | 'statutory' | 'complete';

export interface CompliancePlan {
  id: CompliancePlanTier;
  name: string;
  description: string;
  monthlyPrice: number;
  annualPrice: number;
  targetAudience: string;
  includes: string[];
  excludes?: string[];
  tasks: ComplianceTask[];
  features: string[];
}

export interface ComplianceTask {
  id: string;
  name: string;
  category: string;
  frequency: 'monthly' | 'quarterly' | 'annual' | 'event-based';
  description: string;
  priority: 'high' | 'medium' | 'low';
  autoGenerated: boolean;
  dependencies?: string[]; // Task IDs that must complete before this
}

export interface ComplianceSubscription {
  id: string;
  userId: string;
  firmId: string;
  planTier: CompliancePlanTier;
  status: 'active' | 'paused' | 'cancelled' | 'expired';
  startDate: Timestamp | Date;
  renewalDate: Timestamp | Date;
  lastTaskGeneration?: Timestamp | Date;
  autoRenew: boolean;
  paymentMethodId?: string;
  createdAt: Timestamp | Date;
  updatedAt: Timestamp | Date;
}

/** Task status including QA workflow (Zenith Corporate Mitra) */
export type ComplianceTaskExecutionStatus =
  | 'pending'
  | 'assigned'
  | 'in_progress'
  | 'submitted'
  | 'review_required'
  | 'approved'
  | 'rework'
  | 'completed'
  | 'filed'
  | 'closed'
  | 'failed';

export type QAReviewStatus = 'pending' | 'approved' | 'rework';

export interface TaskQA {
  required: boolean;
  reviewerAssociateId?: string;
  reviewerLevelRequired: 'CM-L3' | 'CM-L4';
  reviewStatus: QAReviewStatus;
  reviewNotes?: string;
  reviewedAt?: Timestamp | Date;
}

export interface ComplianceTaskExecution {
  id: string;
  subscriptionId: string;
  userId: string;
  firmId: string;
  taskId: string; // Reference to ComplianceTask.id
  taskName: string;
  status: ComplianceTaskExecutionStatus;
  assignedToInternalTeam: boolean; // Always true - ICAI compliance
  dueDate: Timestamp | Date;
  completedAt?: Timestamp | Date;
  filedAt?: Timestamp | Date;
  filingDetails?: {
    formType: string;
    period: string;
    filingDate?: Timestamp | Date;
    acknowledgmentNumber?: string;
  };
  internalNotes?: string;
  assignedTo?: string; // Corporate Mitra / Associate code (no client names - ICAI compliant)
  caReviewer?: string; // CA reviewer code for Enterprise plan tasks
  sopReference?: string; // SOP reference for task execution
  platformOwned: true; // Always true - ZenithBooks as principal
  /** QA workflow (Zenith Corporate Mitra) */
  qa?: TaskQA;
  createdAt: Timestamp | Date;
  updatedAt: Timestamp | Date;
}

export interface ComplianceAuditLog {
  id: string;
  subscriptionId: string;
  userId: string;
  firmId: string;
  action: 'plan_subscribed' | 'plan_updated' | 'plan_cancelled' | 'task_generated' | 'task_assigned' | 'task_completed' | 'filing_completed';
  details: Record<string, any>;
  performedBy: 'system' | string; // 'system' or userId
  performedAt: Timestamp | Date;
  ipAddress?: string;
}

